name="umair"
name2=len(name)
print(name2)
print(name[0:2])
print(name[-5:-3])
print(name[1])
ab="umair i\ns a\b good\a bo\t\by"
print(ab)
print(name.replace('a','vfg'))
print(name.upper())
print(name.lower())
print(name.encode())
print(name.startswith('u'))
print(name.endswith('r'))
print(name.rzfill(56))