# i=0
# while(i<6):
#     print(i)
#     i=i+1

# l = [1, "Harry", False, "This", "Rohan", "Shubham", "Shubhi"]

# index = 0

# while(index<len(l)):
#     print(l[index])
#     index +=1
# l=[1,"index",5,69,25,36]
# for i in l:
#     print(i)
# else:print("done")
for i in range(1, 50, 5):  # Loop from 1 to 49, incrementing by 5
    if i == 45:
        continue  # Skip printing 45

    print(i)  # Print i
